# Generated by Django 6.0.4 on 2026-05-02 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='feedbacks/'),
        ),
    ]
